from calibrations import main, normal, until

r = main(
    [
        {"languages": {"Hittite"}, "d": normal(3400, 100)},
        {"languages": {"Vedic_Sanskrit"}, "d": normal(3250, 250)},
        {"languages": {"Avestan"}, "d": normal(2500, 50)},
        {"languages": {"Ancient_Greek"}, "d": normal(2450, 50)},
        {"languages": {"Latin"}, "d": normal(2150, 50)},
        {"languages": {"Gothic"}, "d": normal(1650, 25)},
        {"languages": {"Old_High_German"}, "d": normal(1150, 50)},
        {"languages": {"Old_English"}, "d": normal(1000, 50)},
        {"languages": {"Old_Norse"}, "d": normal(800, 50)},
        {"languages": {"Classical_Armenian"}, "d": normal(1550, 50)},
        {"languages": {"Tocharian_B"}, "d": normal(1350, 150)},
        {"languages": {"Old_Irish"}, "d": normal(1200, 100)},
        {"languages": {"Cornish"}, "d": normal(300, 100)},
        {"languages": {"Old_Church_Slavic"}, "d": normal(1000, 50)},
        {
            "languages": {
                "Gothic",
                "Old_Norse",
                "Icelandic",
                "Faroese",
                "Norwegian",
                "Swedish",
                "Danish",
                "Old_English",
                "English",
                "Frisian",
                "Old_High_German",
                "German",
                "Luxembourgish",
                "Swiss_German",
                "Dutch",
                "Flemish",
                "Afrikaans",
            },
            "name": "Germanic",
            "d": {"tag": "Uniform", "name": "distr", "lower": "2250", "upper": "20000"},
        },
        {
            "languages": {
                "Latin",
                "Nuorese",
                "Cagliari",
                "Romanian",
                "Catalan",
                "Portuguese",
                "Spanish",
                "French",
                "Provencal",
                "Walloon",
                "Ladin",
                "Romansh",
                "Friulian",
                "Italian",
            },
            "name": "Romance",
            "d": {"tag": "Uniform", "name": "distr", "lower": "1750", "upper": "20000"},
        },
        {
            "languages": {
                "Old_Norse",
                "Icelandic",
                "Faroese",
                "Norwegian",
                "Swedish",
                "Danish",
            },
            "name": "Scandinavian",
            "d": {"tag": "Uniform", "name": "distr", "lower": "1500", "upper": "20000"},
        },
        {
            "languages": {
                "Czech",
                "Slovak",
                "Polish",
                "Upper_Sorbian",
                "Ukrainian",
                "Belarusian",
                "Russian",
                "Slovenian",
                "Macedonian",
                "Bulgarian",
                "Serbian",
                "Old_Church_Slavic",
            },
            "name": "Slavic",
            "d": {"tag": "Uniform", "name": "distr", "lower": "1500", "upper": "20000"},
        },
        {
            "languages": {
                "Lithuanian",
                "Latvian",
            },
            "name": "East_Baltic",
            "d": {"tag": "Uniform", "name": "distr", "lower": "1300", "upper": "20000"},
        },
        {
            "languages": {
                "Welsh",
                "Breton",
                "Cornish",
            },
            "name": "British_Celtic",
            "d": {"tag": "Uniform", "name": "distr", "lower": "1250", "upper": "20000"},
        },
        {
            "languages": {
                "Irish",
                "Scots_Gaelic",
            },
            "name": "Modern_Irish-Scots_Gaelic",
            "d": {"tag": "Uniform", "name": "distr", "lower": "1050", "upper": "20000"},
        },
        {
            "languages": {
                "Tajik",
                "Persian",
            },
            "name": "Persian-Tajik",
            "d": {"tag": "Uniform", "name": "distr", "lower": "750", "upper": "20000"},
        },
    ]
)
